apiVersion: apps/v1
kind: Deployment
metadata:
  name: ht-deployment
  labels:
    app: httpd
spec:
  template:
    metadata:
      labels:
        app: httpd
    spec:
      container:
        - name: httpd-con
          image: avanikasingh/ht:1.0
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      app: httpd    
