apiVersion: apps/v1
kind: Deployment
metadata:
  name: abcd-deployment
  labels:
    app: httpd
spec:
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd-con
          image: avanikasingh/abcd:1.0
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      app: httpd    
